/**

 * @description - error codes

 */
export namespace ErrorCodes {
    // API Validation Errors
    export const ERR_API_INVALID_REQUEST = 'INVALID_REQUEST';
    export const ERR_API_USER_BLOCKED = 'USER_ACCESS_BLOCKED';
    export const ERR_API_DUPLICATE_REQUEST = 'DUPLICATE_REQUEST';
    export const ERR_API_INVALID_ID = 'INVALID_ID';
    export const ERR_API_INVALID_KEY = 'INVALID_KEY';
    export const ERR_API_UPDATE_RESOURCE = 'ERROR_UPDATE_RESOURCE';
    export const ERR_API_INVALID_ACCESS_CODE = 'INVALID_ACCESS_CODE';
    export const ERR_API_INVALID_PASSWORD = 'INVALID_PASSWORD';
    export const FAILED_TO_UPDATE_MEMBER = 'FAILED_MEMBER_UPDATE';
    export const ERR_API_INVALID_ROUTE = 'INVALID_ROUTE';
    export const ERR_API_PERMISSION_DENIED = 'PERMISSION_DENIED';
    export const ERR_API_ADMIN_DELETE_NOT_ALLLOWED = 'ADMIN_DELETE_NOT_ALLLOWED';
    export const ERR_API_UPLOAD_RESOURCE = 'FAILED_UPLOAD_RESOURCE';
    export const ERR_API_FAILED_CANCEL_REQUEST = 'FAILED_CANCEL_REQUEST';
    export const ERR_API_CERTIFICATE_NOT_VERIFIED = 'CERTIFICATE_NOT_VERIFIED';
    export const ERR_API_DOCUMENT_NOT_VERIFIED = 'DOCUMENT_NOT_VERIFIED';
    export const ERR_API_DOCUMENTS_NOT_UPLOADED = 'DOCUMENTS_NOT_UPLOADED';
    export const ERR_API_REQUEST_ALREADY_ASSIGNED = 'REQUEST_ALREADY_ASSIGNED';
    export const ERR_API_NO_ROUTE_ACCEPTED = 'NO_ROUTE_ACCEPTED';
    export const ERR_API_INVALID_ROUTE_ACCEPTED = 'INVALID_ROUTE_ACCEPTED';
    export const ERR_API_ROUTE_ALREADY_ACCEPTED = 'ROUTE_ALREADY_ACCEPTED';
    export const ERR_API_REQUEST_ALREADY_CANCELED = 'REQUEST_ALREADY_CANCELED';
    export const ERR_API_DUPLICATE_BILLING_CODE = 'DUPLICATE_BILLING_CODE';
    export const ERR_API_INVALID_APPOINTMENT_TIME = 'INVALID_APPOINTMENT_TIME';
    export const ERR_API_ALREADY_VERIFIED = 'ALREADY_VERIFIED';
    export const ERR_API_DUPLICATE_SETTING_KEY = 'DUPLICATE_SETTING_KEY';
    export const ERR_API_DUPLICATE_SEQUENCE_NAME = 'DUPLICATE_SEQUENCE_NAME';
    export const ERR_API_INVALID_MEETING_TIME = 'INVALID_MEETING_TIME';
    export const ERR_API_NO_SUBSCRIPTION_PLAN_FOUND = 'NO_SUBSCRIPTION_PLAN_FOUND';
    export const ERR_API_NO_SUBSCRIPTION_PLAN_EXPIRED = 'NO_SUBSCRIPTION_PLAN_EXPIRED';
    export const ERR_API_SUBSCRIPTION_PLAN_LIMIT_EXCEEDED = 'SUBSCRIPTION_PLAN_LIMIT_EXCEEDED';
    export const ERR_API_DUPLICATE_COMPANY_NAME = 'DUPLICATE_COMPANY_NAME';
    export const ERR_API_DUPLICATE_DRIVER_EMAIL = 'DUPLICATE_DRIVER_EMAIL';
    export const ERR_API_DELETE_RESOURCE = 'FAILED_DELETE_RESOURCE';

    // Admin Error codes
    export const ERR_API_DUPLICATE_HOST = 'DUPLICATE_HOST';

    // Language Error codes
    export const ERR_API_DUPLICATE_LANGUAGE = 'DUPLICATE_LANGUAGE';

    // Patient Error Codes
    export const ERR_API_DUPLICATE_PATIENT = 'DUPLICATE_PATIENT';

    // Provider Error code
    export const ERR_API_DUPLICATE_PROVIDER = 'DUPLICATE_PROVIDER';
    
    export const ERR_API_DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE';

    export const ERR_API_RESOURCE_NOT_FOUND = 'DUPLICATE_RESOURCE';

    // User registration
    export const ERR_API_USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';

    // DB Errors
    export const ERR_DB_INVALID_ID = 'INVALID_ID';
    export const ERR_DB_READ_EXCEPTION = 'DB_READ_OPERATION_ERROR';
    export const ERR_DB_WRITE_EXCEPTION = 'DB_WRITE_OPERATION_ERROR';
    export const ERR_DB_INVALID_QUERY_EXCEPTION = 'DB_INVALID_QUERY';
    export const ERR_SERVICE_DB_CONNECTION = 'DB_CONNECT_ERROR';
    export const ERR_SERVICE_DB_SEQ_NOT_FOUND = 'SEQUENCE_NOT_FOUND';

    // Service Errors
    export const ERR_SERVICE_EXCEPTION = 'SERVICE_EXCEPTION';
    export const ERR_PDF_SERVICE_EXCEPTION = 'FAILED_TO_GENERATE_PDF';
    export const ERR_CALENDAR_EVENT_CREATE_EXCEPTION = 'FAILED_TO_CREATE_CALENDAR_EVENT';
    export const ERR_FAILED_TO_ACTIVATE_SUBSCRIPTION_PLAN = 'FAILED_TO_ACTIVATE_SUBSCRIPTION_PLAN';

    // Payment Errors
    export const ERR_STRIPE_FAILED_ADD_CUSTOMER = 'FAILED_ADD_CUSTOMER';
    export const ERR_STRIPE_FAILED_GET_PAYEMENT_SOURCE = 'FAILED_GET_PAYMENT_SOURCE';
    export const ERR_STRIPE_FAILED_ADD_PAYMENT_SOURCE = 'FAILED_ADD_PAYMENT_SOURCE';
    export const ERR_STRIPE_FAILED_DELETE_PAYMENT_SOURCE = 'FAILED_DELETE_PAYMENT_SOURCE';
    export const ERR_STRIPE_FAILED_UPDATE_PAYMENT_SOURCE = 'FAILED_UPDATE_PAYMENT_SOURCE';
    export const ERR_STRIPE_FAILED_TO_AUTHORIZE_PAYMENT = 'FAILED_TO_AUTHORIZE_PAYMENT';
    export const ERR_GOOGLE_FAILED_FIND_DISTANCE = 'FAILED_FIND_DISTANCE';
    export const ERR_GOOGLE_FAILED_FIND_DIRECTION = 'FAILED_FIND_DIRECTION';
    export const ERR_STRIPE_FAILED_GET_CUSTOMER = 'FAILED_GET_PAYMENT_CUSTOMER';
    export const ERR_STRIPE_FAILED_VERIFY_PAYMENT_SOURCE = 'FAILED_VERIFY_PAYMENT_SOURCE';
    export const ERR_STRIPE_FAILED_CREATE_ACCOUNT = 'FAILED_CREATE_CUSTOM_ACCOUNT';
    export const ERR_STRIPE_FAILED_REFUND = 'FAILED_TO_REFUND';
    export const ERR_API_REFUND_NO_PAYMENT_TO_REFUND = 'NO_PAYMENT_TO_REFUND';
    export const ERR_API_REFUND_INVALID_AMOUNT = 'INVALID_REFUND_AMOUNT';

    // Meeting and Calendar Errors
    export const ERR_API_CREATE_ZOOM_MEETING_EXCEPTION = 'FAILED_TO_CREATE_ZOOM_MEETING';
    export const ERR_API_CREATE_CALENDAR_EVENT_EXCEPTION = 'FAILED_TO_CREATE_EVENT';
    export const ERR_API_DELETE_MEETING_EXCEPTION = 'FAILED_TO_DELETE_MEETING';
    export const ERR_API_CANCEL_CALENDAR_EVENT_EXCEPTION = 'FAILED_TO_CANCEL_EVENT';
    export const ERR_API_GET_CALENDAR_EVENT_EXCEPTION = 'FAILED_TO_GET_EVENT';
    export const ERR_API_RESCHEDULE_MEETING_EXCEPTION = 'FAILED_TO_RESCHEDULE_MEETING';
    export const ERR_API_RESCHEDULE_CALENDAR_EVENT_EXCEPTION = 'FAILED_TO_RESCHEDULE_EVENT';
    export const ERR_API_GET_MEETING = 'FAILED_TO_GET_MEETING';

    // Bill.com error codes
    export const ERR_API_FAILED_TO_GET_SESSION_TOKEN = 'FAILED_TO_GET_SESSION_TOKEN';
    export const ERR_API_FAILED_TO_CREATE_PAYABLE_ACCOUNT = 'FAILED_TO_CREATE_PAYABLE_ACCOUNT';
    export const ERR_API_FAILED_TO_CREATE_BILL = 'FAILED_TO_CREATE_BILL';
}
